% Import_SIFTResults.m
%
% The script reads in the SIFTResults.csv file
% Auto-generated by MATLAB on 10-Jun-2020 00:07:14

%% Setup the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 11);

% Specify range and delimiter
opts.DataLines = [2, Inf];
opts.Delimiter = ";";

% Specify column names and types
opts.VariableNames = ["idx", "fileA", "fileB", "m00", "m10", "m01", "m11", "m02", "m12", "cost", "success"];
opts.VariableTypes = ["double", "string", "string", "double", "double", "double", "double", "double", "double", "double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, ["fileA", "fileB"], "WhitespaceRule", "preserve");
opts = setvaropts(opts, ["fileA", "fileB"], "EmptyFieldRule", "auto");

% Import the data
SIFTResults = readtable("/Users/Elisabeth/Documents/uni_ordner_april_15/Uppsala/MultimodalRegistration/CodeRelease/SIFT/SIFTResults.csv", opts);


%% Clear temporary variables
clear opts