% ImportMetaData.m
%
% Auto-generated by MATLAB on 09-Jun-2020 13:29:12.
%
% The script reads in the metadata.csv file

%% Setup the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 18);

% Specify range and delimiter
opts.DataLines = [2, Inf];
opts.Delimiter = ";";

% Specify column names and types
opts.VariableNames = ["Filename", "X1_Ref", "Y1_Ref", "X2_Ref", "Y2_Ref", "X3_Ref", "Y3_Ref", "X4_Ref", "Y4_Ref", "X1_Trans", "Y1_Trans", "X2_Trans", "Y2_Trans", "X3_Trans", "Y3_Trans", "X4_Trans", "Y4_Trans", "Displacement"];
opts.VariableTypes = ["string", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, "Filename", "WhitespaceRule", "preserve");
opts = setvaropts(opts, "Filename", "EmptyFieldRule", "auto");

% Import the data
metadata = readtable("/Users/Elisabeth/Documents/uni_ordner_april_15/Uppsala/MultimodalRegistration/CodeRelease/MI/metadata.csv", opts);


%% Clear temporary variables
clear opts