% ImportResultfileTemplate.m
%
% Auto-generated by MATLAB on 09-Jun-2020 13:29:12.
%
% The script reads in the ResultfileTemplate.csv file

%% Setup the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 36);

% Specify range and delimiter
opts.DataLines = [2, Inf];
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["Filename", "ReferenceImage", "FloatingImage", "Method", "X1_Ref", "Y1_Ref", "X2_Ref", "Y2_Ref", "X3_Ref", "Y3_Ref", "X4_Ref", "Y4_Ref", "X1_Trans", "Y1_Trans", "X2_Trans", "Y2_Trans", "X3_Trans", "Y3_Trans", "X4_Trans", "Y4_Trans", "X1_Recover", "Y1_Recover", "X2_Recover", "Y2_Recover", "X3_Recover", "Y3_Recover", "X4_Recover", "Y4_Recover", "Displacement", "Tx", "Ty", "AngleDegree", "AngleRad", "Error", "DisplacementCategory", "VarName36"];
opts.VariableTypes = ["string", "string", "string", "string", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "string", "categorical", "string"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, ["Filename", "ReferenceImage", "FloatingImage", "Method", "Error", "VarName36"], "WhitespaceRule", "preserve");
opts = setvaropts(opts, ["Filename", "ReferenceImage", "FloatingImage", "Method", "Error", "DisplacementCategory", "VarName36"], "EmptyFieldRule", "auto");
opts = setvaropts(opts, ["X1_Recover", "Y1_Recover", "X2_Recover", "Y2_Recover", "X3_Recover", "Y3_Recover", "X4_Recover", "Y4_Recover"], "TrimNonNumeric", true);
opts = setvaropts(opts, ["X1_Recover", "Y1_Recover", "X2_Recover", "Y2_Recover", "X3_Recover", "Y3_Recover", "X4_Recover", "Y4_Recover"], "ThousandsSeparator", ",");

% Import the data
ResultfileTemplate = readtable("/Users/Elisabeth/Documents/uni_ordner_april_15/Uppsala/MultimodalRegistration/CodeRelease/MI/ResultfileTemplate.csv", opts);


%% Clear temporary variables
clear opts